# Chapter 4 - Workflow: Code Style

Este capítulo presentará los puntos más importantes de la guía de estilo tidyverse, que se utiliza a lo largo de este libro.

Estilizar el código te parecerá tedioso al principio, pero si lo practicas, pronto se convertirá en algo natural

In [ ]:
install.packages('nycflights13')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(tidyverse)
library(nycflights13)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Nombres

In [ ]:
# Los nombres de las variables (las creadas por <- y mutate()) deben utilizar sólo letras minúsculas, números y _. Utiliza _ para separar las palabras dentro de un nombre.

# Strive for:
short_flights <- flights |> filter(air_time < 60)

# Avoid
SHORTFLIGHTS <- flights |> filter(air_time < 60)

# Como regla general, es mejor preferir nombres largos y descriptivos que sean fáciles de entender que nombres concisos que sean rápidos de escribir. Los nombres cortos ahorran relativamente poco tiempo al escribir código, pero pueden consumir mucho tiempo cuando vuelvas a un código antiguo y te veas obligado a descibrar una abreviatura críptica.

## Espacios

In [ ]:
# Pon espacios a ambos lados de los operadores amtemáticos aparte de ^ (es decir, +, -, , ==, <, ...) y arededor del operadore de asignación

# Strive for
z <- (a + b)^2 / d

# Avoid
z<-( a + b ) ^ 2/d

In [ ]:
# No pongas espacios dentro o fuera de los paréntesis en las lamadas a funciones normales. Pon siempre un espacio despues de una coma, como en el ingles estándar.

# Strive for
mean(x, na.rm = TRUE)

# Avoid
mean (x ,na.rm=TRUE)

In [ ]:
# Está bien añadir espacios extra si mejora la alineación. Por ejemplo, si estás creadndo múltiples variables un mutate() puedes añadir espacios para que todas las = queden alineadas. Así será más fácil hojear el código.

flights |>
  mutate(
    speed       = distance / air_time,
    dep_hour    = dep_time %/% 100,
    dep_minute  = dep_time %% 100
  )
# Cómo dep_time estpa en formato HMM, utilizamos la dicisión entera (%/%) para obtener la hora y el resto(%%) para obtener el minuto.

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 1     1   517      515             2         830      819
2      2013 1     1   533      529             4         850      830
3      2013 1     1   542      540             2         923      850
4      2013 1     1   544      545            -1        1004     1022
5      2013 1     1   554      600            -6         812      837
6      2013 1     1   554      558            -4         740      728
7      2013 1     1   555      600            -5         913      854
8      2013 1     1   557      600            -3         709      723
9      2013 1     1   557      600            -3         838      846
10     2013 1     1   558      600            -2         753      745
11     2013 1     1   558      600            -2         849      851
12     2013 1     1   558      600            -2         853      856
13     2013 1     1   558      600            -2         924      917
14     2013 1     1   558      600            -2         923      937
15     2013 1     1   559      600            -1         941      910
16     2013 1     1   559      559             0         702      706
17     2013 1     1   559      600            -1         854      902
18     2013 1     1   600      600             0         851      858
19     2013 1     1   600      600             0         837      825
20     2013 1     1   601      600             1         844      850
21     2013 1     1   602      610            -8         812      820
22     2013 1     1   602      605            -3         821      805
23     2013 1     1   606      610            -4         858      910
24     2013 1     1   606      610            -4         837      845
25     2013 1     1   607      607             0         858      915
26     2013 1     1   608      600             8         807      735
27     2013 1     1   611      600            11         945      931
28     2013 1     1   613      610             3         925      921
29     2013 1     1   615      615             0        1039     1100
30     2013 1     1   615      615             0         833      842
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     30  2123     2125            -2       2223     2247
336748 2013 9     30  2127     2129            -2       2314     2323
336749 2013 9     30  2128     2130            -2       2328     2359
336750 2013 9     30  2129     2059            30       2230     2232
336751 2013 9     30  2131     2140            -9       2225     2255
336752 2013 9     30  2140     2140             0         10       40
336753 2013 9     30  2142     2129            13       2250     2239
336754 2013 9     30  2145     2145             0        115      140
336755 2013 9     30  2147     2137            10         30       27
336756 2013 9     30  2149     2156            -7       2245     2308
336757 2013 9     30  2150     2159            -9       2250     2306
336758 2013 9     30  2159     1845           194       2344     2030
336759 2013 9     30  2203     2205            -2       2339     2331
336760 2013 9     30  2207     2140            27       2257     2250
336761 2013 9     30  2211     2059            72       2339     2242
336762 2013 9     30  2231     2245           -14       2335     2356
336763 2013 9     30  2233     2113            80        112       30
336764 2013 9     30  2235     2001           154         59     2249
336765 2013 9     30  2237     2245            -8       2345     2353
336766 2013 9     30  2240     2245            -5       2334     2351
336767 2013 9     30  2240     2250           -10       2347        7
336768 2013 9     30  2241     2246            -5       2345        1
336769 2013 9     30  2307     2255            12       2359     2358
336770 2013 9     30  2349     2359           -10        325      350
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier ⋯ origin dest air_time distance hour minute
1       11       UA      ⋯ EWR    IAH  227      1400     5    15
2       20       UA      ⋯ LGA    IAH  227      1416     5    29
3       33       AA      ⋯ JFK    MIA  160      1089     5    40
4      -18       B6      ⋯ JFK    BQN  183      1576     5    45
5      -25       DL      ⋯ LGA    ATL  116       762     6     0
6       12       UA      ⋯ EWR    ORD  150       719     5    58
7       19       B6      ⋯ EWR    FLL  158      1065     6     0
8      -14       EV      ⋯ LGA    IAD   53       229     6     0
9       -8       B6      ⋯ JFK    MCO  140       944     6     0
10       8       AA      ⋯ LGA    ORD  138       733     6     0
11      -2       B6      ⋯ JFK    PBI  149      1028     6     0
12      -3       B6      ⋯ JFK    TPA  158      1005     6     0
13       7       UA      ⋯ JFK    LAX  345      2475     6     0
14     -14       UA      ⋯ EWR    SFO  361      2565     6     0
15      31       AA      ⋯ LGA    DFW  257      1389     6     0
16      -4       B6      ⋯ JFK    BOS   44       187     5    59
17      -8       UA      ⋯ EWR    LAS  337      2227     6     0
18      -7       B6      ⋯ LGA    FLL  152      1076     6     0
19      12       MQ      ⋯ LGA    ATL  134       762     6     0
20      -6       B6      ⋯ EWR    PBI  147      1023     6     0
21      -8       DL      ⋯ LGA    MSP  170      1020     6    10
22      16       MQ      ⋯ LGA    DTW  105       502     6     5
23     -12       AA      ⋯ EWR    MIA  152      1085     6    10
24      -8       DL      ⋯ JFK    ATL  128       760     6    10
25     -17       UA      ⋯ EWR    MIA  157      1085     6     7
26      32       MQ      ⋯ EWR    ORD  139       719     6     0
27      14       UA      ⋯ JFK    SFO  366      2586     6     0
28       4       B6      ⋯ JFK    RSW  175      1074     6    10
29     -21       B6      ⋯ JFK    SJU  182      1598     6    15
30      -9       DL      ⋯ EWR    ATL  120       746     6    15
⋮      ⋮         ⋮       ⋱ ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
336747 -24       EV      ⋯ LGA    CHO   45       305     21   25
336748  -9       EV      ⋯ EWR    CLT   72       529     21   29
336749 -31       B6      ⋯ JFK    DEN  213      1626     21   30
336750  -2       EV      ⋯ LGA    RIC   45       292     20   59
336751 -30       MQ      ⋯ JFK    DCA   36       213     21   40
336752 -30       AA      ⋯ JFK    LAX  298      2475     21   40
336753  11       EV      ⋯ EWR    PWM   47       284     21   29
336754 -25       B6      ⋯ JFK    SJU  192      1598     21   45
336755   3       B6      ⋯ LGA    FLL  139      1076     21   37
336756 -23       UA      ⋯ EWR    BOS   37       200     21   56
336757 -16       EV      ⋯ EWR    MHT   39       209     21   59
336758 194       9E      ⋯ JFK    BUF   50       301     18   45
336759   8       EV      ⋯ LGA    BGR   61       378     22    5
336760   7       MQ      ⋯ LGA    BNA   97       764     21   40
336761  57       EV      ⋯ EWR    STL  120       872     20   59
336762 -21       B6      ⋯ JFK    PWM   48       273     22   45
336763  42       UA      ⋯ EWR    SFO  318      2565     21   13
336764 130       B6      ⋯ JFK    MCO  123       944     20    1
336765  -8       B6      ⋯ JFK    BTV   43       266     22   45
336766 -17       B6      ⋯ JFK    SYR   41       209     22   45
336767 -20       B6      ⋯ JFK    BUF   52       301     22   50
336768 -16       B6      ⋯ JFK    ROC   47       264     22   46
336769   1       B6      ⋯ JFK    BOS   33       187     22   55
336770 -25       B6      ⋯ JFK    PSE  196      1617     23   59
336771  NA       EV      ⋯ LGA    BNA   NA       764     18   42
336772  NA       9E      ⋯ JFK    DCA   NA       213     14   55
336773  NA       9E      ⋯ LGA    SYR   NA       198     22    0
336774  NA       MQ      ⋯ LGA    BNA   NA       764     12   10
336775  NA       MQ      ⋯ LGA    CLE   NA       419     11   59
336776  NA       MQ      ⋯ LGA    RDU   NA       431      8   40
       time_hour           speed    dep_hour dep_minute
1      2013-01-01 05:00:00 6.167401 5        17
2      2013-01-01 05:00:00 6.237885 5        33
3      2013-01-01 05:00:00 6.806250 5        42
4      2013-01-01 05:00:00 8.612022 5        44
5      2013-01-01 06:00:00 6.568966 5        54
6      2013-01-01 05:00:00 4.793333 5        54
7      2013-01-01 06:00:00 6.740506 5        55
8      2013-01-01 06:00:00 4.320755 5        57
9      2013-01-01 06:00:00 6.742857 5        57
10     2013-01-01 06:00:00 5.311594 5        58
11     2013-01-01 06:00:00 6.899329 5        58
12     2013-01-01 06:00:00 6.360759 5        58
13     2013-01-01 06:00:00 7.173913 5        58
14     2013-01-01 06:00:00 7.105263 5        58
15     2013-01-01 06:00:00 5.404669 5        59
16     2013-01-01 05:00:00 4.250000 5        59
17     2013-01-01 06:00:00 6.608309 5        59
18     2013-01-01 06:00:00 7.078947 6         0
19     2013-01-01 06:00:00 5.686567 6         0
20     2013-01-01 06:00:00 6.959184 6         1
21     2013-01-01 06:00:00 6.000000 6         2
22     2013-01-01 06:00:00 4.780952 6         2
23     2013-01-01 06:00:00 7.138158 6         6
24     2013-01-01 06:00:00 5.937500 6         6
25     2013-01-01 06:00:00 6.910828 6         7
26     2013-01-01 06:00:00 5.172662 6         8
27     2013-01-01 06:00:00 7.065574 6        11
28     2013-01-01 06:00:00 6.137143 6        13
29     2013-01-01 06:00:00 8.780220 6        15
30     2013-01-01 06:00:00 6.216667 6        15
⋮      ⋮                   ⋮        ⋮        ⋮
336747 2013-09-30 21:00:00 6.777778 21       23
336748 2013-09-30 21:00:00 7.347222 21       27
336749 2013-09-30 21:00:00 7.633803 21       28
336750 2013-09-30 20:00:00 6.488889 21       29
336751 2013-09-30 21:00:00 5.916667 21       31
336752 2013-09-30 21:00:00 8.305369 21       40
336753 2013-09-30 21:00:00 6.042553 21       42
336754 2013-09-30 21:00:00 8.322917 21       45
336755 2013-09-30 21:00:00 7.741007 21       47
336756 2013-09-30 21:00:00 5.405405 21       49
336757 2013-09-30 21:00:00 5.358974 21       50
336758 2013-09-30 18:00:00 6.020000 21       59
336759 2013-09-30 22:00:00 6.196721 22        3
336760 2013-09-30 21:00:00 7.876289 22        7
336761 2013-09-30 20:00:00 7.266667 22       11
336762 2013-09-30 22:00:00 5.687500 22       31
336763 2013-09-30 21:00:00 8.066038 22       33
336764 2013-09-30 20:00:00 7.674797 22       35
336765 2013-09-30 22:00:00 6.186047 22       37
336766 2013-09-30 22:00:00 5.097561 22       40
336767 2013-09-30 22:00:00 5.788462 22       40
336768 2013-09-30 22:00:00 5.617021 22       41
336769 2013-09-30 22:00:00 5.666667 23        7
336770 2013-09-30 23:00:00 8.250000 23       49
336771 2013-09-30 18:00:00       NA NA       NA
336772 2013-09-30 14:00:00       NA NA       NA
336773 2013-09-30 22:00:00       NA NA       NA
336774 2013-09-30 12:00:00       NA NA       NA
336775 2013-09-30 11:00:00       NA NA       NA
336776 2013-09-30 08:00:00       NA NA       NA

## Tuberías |>

In [ ]:
# |> siempre debe ir precesido de un espacio y, por lo general, debe ser el último elemento de la línea. Esto facilita añadir nuevos pasos, reorganizar pasos existentes, modificar elementos dentro de un paso y obtener una visión de 10.000 pies hojeando los verbos de la parte izquierda.
# Strive for
flights |>
  filter(lis.na(ar_delay), lis.na(tailnum)) |>
    count(dest)

# Avoid
flights|>filter(lis.na(ar_delay), lis.na(tailnum))|>count(dest)

In [ ]:
# SI la función que estás canalizando tiene argumentos con nombre (como mutate() o sumarize()), coloca cada argumento en un línea nueva. Si la función no tiene argumentos con nombre (como select() o filter()), mantenlo todo en una linea a menos que quepa, en cuyo caso debes poner cada argumento en su propia linea.
# Strive for
flights |>
  group_by(tailnum) |>
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )
# Avoid
flights |>
  group_by(
    tailnum
    ) |>
    summarize(delay = (arr_delay, na.rm = TRUE), n = n())

In [ ]:
# Está bien eludir algunas de estas reglas si tu fragmento cabe fácilmente en una línea. Pero, según nuestra experiencia colectiva, es habitual que los fragmentos cortos se alarguen,  por lo que normalmente ahorrarás tiempo a largo palzo si empiezas con todo el espacio vertical que necesites:
# This fits compactly on one line
df |> mutate(y = x + 1)

# While this takes up 4x as many lines, it's easily extended to more variables and more steps in the future
df |>
  mutate(
  y = x + 1
  )

In [ ]:
# Desconfía de escribir tuberías muy largas, digamos de mpas de 10-15 líneas. Intenta dividirlas en subtareas más pequeñas, dando a ada tarea un nombre informativo. Los nombres ayudarán al lector a saber qupe está ocurriendo y le facilitarpan la comprobación de que los resultados intemedios son los esperados

## ggplot2

In [ ]:
# Las mismas reglas básicas que se aplican a la tubería también se aplican a ggplot2; sólo tienes que tratar + del mismo modo que |>
flights |>
  group_by(month) |>
  sumarize(
    delay = mean(arr_delay, na.rm = TRUE)
  ) |>
  ggplot(aes(x = month, y = delay)) +
  geom_point() +
  geom_line()
# Si no caben todos los argumentos de una función en una sola línea, pon cada argumento en su propia línea
flights |>
  group_by(dest) |>
  summarize(
    distance = mean(distance),
    speed = mean(distance / air_time, na.rm = TRUE)
  ) |>
  ggplot(aes(x = distance,y = speed)) +
  geom_smooth(
    method = 'loess',
    span = 0.5,
    se = FALSE,
    color = 'white',
    linewidth = 4
  ) +
  geom_point()

# Observa la transición de |> a +. Desearíamos que esta transición no fuera necesaria, pero por desgracia, ggplot2 se escribió antes de que se descubriera la tubería

## Ejercicios

In [ ]:
#1. Modifica el estilo de las siguientes tuberías siguiendo las pautas anteriores.

flights |>
  filter(dest == 'IAH') |>
  group_by(year, month, day) |>
  summarize(
    n = n(),
    delay = mean(arr_delay, na.rm = TRUE)
  ) |>
  filter(n > 10)

flights |>
  filter(carrier == 'UA', dest %in% c('IAH', 'HOU'),
    sched_dep_time > 0900, sched_arr_time < 2000) |>
  group_by(flight) |>
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n = n()
  ) |>
  filter(n > 10)

`summarise()` has regrouped the output.
ℹ Summaries were computed grouped by year, month, and day.
ℹ Output is grouped by year and month.
ℹ Use `summarise(.groups = "drop_last")` to silence this message.
ℹ Use `summarise(.by = c(year, month, day))` for per-operation grouping
  (`?dplyr::dplyr_by`) instead.

    year month day n  delay
1   2013 1      1  20  17.850000
2   2013 1      2  20   7.000000
3   2013 1      3  19  18.315789
4   2013 1      4  20  -3.200000
5   2013 1      5  13  20.230769
6   2013 1      6  18   9.277778
7   2013 1      7  19  -7.736842
8   2013 1      8  19   7.789474
9   2013 1      9  19  18.055556
10  2013 1     10  19   6.684211
11  2013 1     11  19 -22.526316
12  2013 1     12  13 -19.923077
13  2013 1     13  18  14.833333
14  2013 1     14  19  17.421053
15  2013 1     15  19  26.105263
16  2013 1     16  19  40.105263
17  2013 1     17  19  -7.894737
18  2013 1     18  19  -5.210526
19  2013 1     19  13   2.153846
20  2013 1     20  18  10.352941
21  2013 1     21  19  19.789474
22  2013 1     22  19  -5.055556
23  2013 1     23  19  -6.947368
24  2013 1     24  19 -15.894737
25  2013 1     25  19 -10.368421
26  2013 1     26  13  -8.384615
27  2013 1     27  18 -16.055556
28  2013 1     28  19 -15.157895
29  2013 1     29  19 -20.842105
30  2013 1     30  19  20.842105
⋮   ⋮    ⋮     ⋮   ⋮  ⋮
336 2013 12     2  22 -6.5000000
337 2013 12     3  22 -8.4545455
338 2013 12     4  22 -3.1363636
339 2013 12     5  22 51.7142857
340 2013 12     6  22 14.8181818
341 2013 12     7  16 18.8666667
342 2013 12     8  18 29.4705882
343 2013 12     9  22 34.5454545
344 2013 12    10  22 60.3529412
345 2013 12    11  22  3.4090909
346 2013 12    12  22  5.3333333
347 2013 12    13  22 -3.0000000
348 2013 12    14  16 54.6666667
349 2013 12    15  19  6.6470588
350 2013 12    16  22 -8.1818182
351 2013 12    17  22 33.4500000
352 2013 12    18  22  8.4090909
353 2013 12    19  21 -6.6190476
354 2013 12    20  21 20.1000000
355 2013 12    21  16 50.1250000
356 2013 12    22  18 28.3333333
357 2013 12    23  23 28.8181818
358 2013 12    24  16  2.3125000
359 2013 12    25  12  7.5833333
360 2013 12    26  18 -0.4444444
361 2013 12    27  18  6.1666667
362 2013 12    28  16  9.5000000
363 2013 12    29  18 23.6111111
364 2013 12    30  19 23.6842105
365 2013 12    31  15 -4.9333333

   flight delay        cancelled n
1   53     12.5000000  2         18
2  112     14.1428571  0         14
3  205     -1.7142857  0         14
4  235     -5.3571429  0         14
5  255     -9.4666667  0         15
6  268     38.6428571  1         15
7  292      6.5714286  0         21
8  318     10.7368421  1         20
9  337     20.0526316  2         21
10 370     17.4545455  0         11
11 377     -9.6666667  2         20
12 384     -0.5714286  0         21
13 385     20.7333333  0         15
14 404     18.3720930  0         43
15 406      6.4666667  0         15
16 410     -1.2727273  0         11
17 418     21.5384615  0         13
18 428      3.0769231  0         13
19 429     19.5882353  2         19
20 475    -11.9090909  0         11
21 488      8.5438596  2         59
22 501     -1.6060606  0         33
23 508     -1.4615385  1         14
24 525      7.1111111  1         55
25 531     -3.6000000  1         16
26 566     -2.4117647  0         17
27 568     62.5454545  1         12
28 572      9.1363636  0         22
29 574    -11.0909091  0         11
30 575     18.7142857  0         14
⋮  ⋮      ⋮            ⋮         ⋮
45 1112     5.26666667 0          15
46 1166    25.78260870 0          23
47 1178     6.79729730 2         150
48 1192    17.25000000 0          12
49 1232     0.11340206 0          97
50 1233     2.72222222 0          18
51 1250    -3.58333333 0          12
52 1251    33.84615385 1          14
53 1257    -6.22916667 2          98
54 1280    -1.71621622 0          74
55 1410    -8.06666667 0          15
56 1421    -9.25000000 0          28
57 1454    -3.18750000 0          16
58 1461    -1.46153846 1          79
59 1496    -5.82608696 0          23
60 1497   -10.00000000 0          11
61 1502     9.12500000 0          16
62 1545   -10.75000000 0          12
63 1565   -13.68181818 0          22
64 1591     3.05882353 0          17
65 1602     2.33333333 0          15
66 1611     0.09677419 0          31
67 1672    12.34782609 0          23
68 1674     7.59090909 0          22
69 1687     7.46666667 0          15
70 1695     2.16753927 1         192
71 1711    -3.82022472 0          89
72 1712    -7.71428571 0          35
73 1740     7.02777778 0          36
74 1744    -1.45871560 0         109